main/urls.py
from django.urls import path
from . import views
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("qui-etes-vous", views.register, name="register"),
    path("inscription_medecin", views.inscription_medecin, name="inscription_medecin"),
    path("login_medecin", views.login_medecin, name="login_medecin"),
    path("acceuil", views.acceuil_medecin, name="acceuil_medecin"),
    path("profile", views.profile, name="profile"),
    path("logout", views.logout_request, name="logout"),
    path("affichage_fichier/<int:id>", views.affichage_fichier, name="affichage_fichier"),
    path("affichage_patient/<int:id>", views.affichage_patient, name="affichage_patient"),
    path("mes_patients", views.liste_des_patients, name="liste_des_patients"),
    path("mes_fichiers", views.liste_des_fichiers, name="liste_des_fichiers"),
    path("predictions", views.predictions, name="predictions"),
    path("stats", views.stats, name="stats"),
    path("ajout_fichier", views.ajout_fichier, name="ajout_fichier"),
    path("ajout_patient", views.ajout_patient, name="ajout_patient"),
    path("ajout_patient_existant", views.ajout_patient_existant, name="ajout_patient_existant"),
    path("ajout_csv", views.ajout_csv, name="ajout_csv"),
    path("affichage_patient/<int:id>/ajout_consultation", views.ajout_consultation, name="ajout_consultation"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pcd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase
from django_mysql.models import ListCharField


class Patient(models.Model):
    objects = models.Manager()  # Ignore IDE warning
    user = models.OneToOneField(User, on_delete=CASCADE)
    photo = models.ImageField(upload_to='images/patients', default='images/patient.png')
    CHOIXGENRE = (('HOMME', 'HOMME'), ('FEMME', 'FEMME'))
    CHOIXREGION = [('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Mannouba', 'Mannouba'),
                   ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Nabeul', 'Nabeul'),
                   ('Zaghouan', 'Zaghouan'), ('Beja', 'Beja'), ('Jendouba', 'Jendouba'),
                   ('Le Kef', 'Le Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'),
                   ('Sousse', 'Sousse'), ('Mahdia', 'Mahdia'), ('Monastir', 'Monastir'),
                   ('Kasserine', 'Kasserine'), ('Sfax', 'Sfax'), ('Gabes', 'Gabes'),
                   ('Kebili', 'Kebili'), ('Gafsa', 'Gafsa'), ('Sidi Bouzid', 'Sidi Bouzid'),
                   ('Tozeur', 'Tozeur'), ('Medenine', 'Medenine'), ('Tataouin', 'Tataouin')]
    genre = models.CharField(max_length=10, choices=CHOIXGENRE, default='HOMME', )
    date_de_naissance = models.DateField(null=True, blank=True)
    region = models.CharField(max_length=20, choices=CHOIXREGION, default="Tunis")

    def __str__(self):
        return str(self.user)


class Medecin(models.Model):
    objects = models.Manager()  # Ignore IDE warning
    user = models.OneToOneField(User, on_delete=CASCADE)
    CHOIXGENRE = (('HOMME', 'HOMME'), ('FEMME', 'FEMME'))
    CHOIXREGION = [('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Mannouba', 'Mannouba'),
                   ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Nabeul', 'Nabeul'),
                   ('Zaghouan', 'Zaghouan'), ('Beja', 'Beja'), ('Jendouba', 'Jendouba'),
                   ('Le Kef', 'Le Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'),
                   ('Sousse', 'Sousse'), ('Mahdia', 'Mahdia'), ('Monastir', 'Monastir'),
                   ('Kasserine', 'Kasserine'), ('Sfax', 'Sfax'), ('Gabes', 'Gabes'),
                   ('Kebili', 'Kebili'), ('Gafsa', 'Gafsa'), ('Sidi Bouzid', 'Sidi Bouzid'),
                   ('Tozeur', 'Tozeur'), ('Medenine', 'Medenine'), ('Tataouin', 'Tataouin')]
    genre = models.CharField(max_length=10, choices=CHOIXGENRE, default='HOMME',)
    date_de_naissance = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='images/medecins', default='images/medecin_login.png')
    patients = models.ManyToManyField(Patient, related_name="medecins", null=True, blank=True)
    region = models.CharField(max_length=20, choices=CHOIXREGION, default="Tunis")
    first_connection = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)


class Partenaire(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)

    def __str__(self):
        return str(self.user)


class FichierCsv(models.Model):
    medecin = models.ForeignKey(Medecin, on_delete=CASCADE, related_name="csv_files")
    csv_file = models.FileField(null=True, blank=True, upload_to='csv/medecins')

    def __str__(self):
        return str(self.csv_file)


class Consultation(models.Model):
    patient = models.ForeignKey(Patient, on_delete=CASCADE, related_name="consultations")
    symptomes = ListCharField(base_field=models.CharField(max_length=30))
    resultat = models.TextField(max_length=2000, null=True, blank=True)
    date = models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return str(self.date)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from tags_input import fields

from main.models import Medecin, FichierCsv, Patient, Partenaire, Consultation


class FormUser(forms.ModelForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    """password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )"""

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            #'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }


class FormUserComplet(forms.ModelForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            #'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }


class FormMedecin(forms.ModelForm):
    class Meta:
        model = Medecin
        fields = ('date_de_naissance', 'genre', 'region')
        widget = {
            'genre': forms.Select,
        }
    date_de_naissance = forms.DateField(
            widget=forms.DateInput(attrs={'class': 'datepicker'}, format='%b %d, %Y'),
            input_formats=('%b %d, %Y',)
    )


class FormPatient(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('date_de_naissance', 'genre', 'region')
        widget = {
            'genre': forms.Select,
            'region': forms.Select,
        }
    date_de_naissance = forms.DateField(
            widget=forms.DateInput(attrs={'class': 'datepicker'}, format='%b %d, %Y'),
            input_formats=('%b %d, %Y',)
    )

"""
class FormMedecinCsv(forms.ModelForm):
    class Meta:
        model = Medecin
        fields = ('csv_file',)"""


class FormMedecinPhoto(forms.ModelForm):
    class Meta:
        model = Medecin
        fields = ('photo',)


class FormAnnee(forms.Form):
    annee = forms.ChoiceField(choices=[('09-10', '09-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'),
                                       ('14-15', '14-15'), ('15-16', '15-16'), ('16-17', '16-17'), ('17-18', '17-18')])
    categorie = forms.ChoiceField(choices=[('Nombre total des cas', 'Nombre total des cas'),
                                           ("Nombre total des cas de grippe par tranches d'âge",
                                            "Nombre total des cas de grippe par tranches d'âge"),
                                           ("Nombre total des cas SARI par tranches d'âge",
                                            "Nombre total des cas SARI par tranches d'âge"),
                                           ("Le pourcentage des cas de grippe et SARI",
                                            "Le pourcentage des cas de grippe et SARI")])


class FormPrediction(forms.Form):
    """algorithme = forms.ChoiceField(choices=[('lstm1', 'lstm1'), ('lstm4', 'lstm4'),
                                            ('machine learning', 'machine learning'),
                                            ('reseaux des neurones', 'reseaux des neurones')])"""


class FormRegion(forms.Form):
    region = forms.ChoiceField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Mannouba', 'Mannouba'),
                                        ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Nabeul', 'Nabeul'),
                                        ('Zaghouan', 'Zaghouan'), ('Beja', 'Beja'), ('Jendouba', 'Jendouba'),
                                        ('Le Kef', 'Le Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'),
                                        ('Sousse', 'Sousse'), ('Mahdia', 'Mahdia'), ('Monastir', 'Monastir'),
                                        ('Kasserine', 'Kasserine'), ('Sfax', 'Sfax'), ('Gabes', 'Gabes'),
                                        ('Kebili', 'Kebili'), ('Gafsa', 'Gafsa'), ('Sidi Bouzid', 'Sidi Bouzid'),
                                        ('Tozeur', 'Tozeur'), ('Medenine', 'Medenine'), ('Tataouin', 'Tataouin')])


class FormPrediction2(forms.Form):
    algorithme = forms.ChoiceField(choices=[('lstm1', 'lstm1'), ('lstm4', 'lstm4'),
                                            ('machine learning', 'machine learning'),
                                            ('reseaux des neurones', 'reseaux des neurones')])


class FormMois(forms.Form):
    mois = forms.ChoiceField(choices=[('january', 'Janvier'), ('february', 'Fevrier'), ('march', 'Mars'),
                                      ('april', 'Avril'), ('may', 'Mai'), ('june', 'Juin'),
                                      ('july', 'Juillet'), ('august', 'Août'), ('september', 'Septembre'),
                                      ('october', 'Octobre'), ('november', 'Novembre'), ('december', 'Decembre')])


class FormCsv(forms.ModelForm):
    class Meta:
        model = FichierCsv
        fields = ('csv_file',)


class FormCsvCreation(forms.Form):
    """region = forms.ChoiceField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Mannouba', 'Mannouba'),
                                    ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Nabeul', 'Nabeul'),
                                    ('Zaghouan', 'Zaghouan'), ('Beja', 'Beja'), ('Jendouba', 'Jendouba'),
                                    ('Le Kef', 'Le Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'),
                                    ('Sousse', 'Sousse'), ('Mahdia', 'Mahdia'), ('Monastir', 'Monastir'),
                                    ('Kasserine', 'Kasserine'), ('Sfax', 'Sfax'), ('Gabes', 'Gabes'),
                                    ('Kebili', 'Kebili'), ('Gafsa', 'Gafsa'), ('Sidi Bouzid', 'Sidi Bouzid'),
                                    ('Tozeur', 'Tozeur'), ('Medenine', 'Medenine'), ('Tataouin', 'Tataouin')])
    mois = forms.ChoiceField(choices=[('january', 'Janvier'), ('february', 'Fevrier'), ('march', 'Mars'),
                                      ('april', 'Avril'), ('may', 'Mai'), ('june', 'Juin'),
                                      ('july', 'Juillet'), ('august', 'Août'), ('september', 'Septembre'),
                                      ('october', 'Octobre'), ('november', 'Novembre'), ('december', 'Decembre')])"""
    grippe_enfant = forms.IntegerField(initial=0)
    sari_enfant = forms.IntegerField(initial=0)
    consultation_enfant = forms.IntegerField(initial=0)
    grippe_adolescent = forms.IntegerField(initial=0)
    sari_adolescent = forms.IntegerField(initial=0)
    consultation_adolescent = forms.IntegerField(initial=0)
    grippe_mur = forms.IntegerField(initial=0)
    sari_mur = forms.IntegerField(initial=0)
    consultation_mur = forms.IntegerField(initial=0)


class FormConsultation(forms.ModelForm):
    class Meta:
        model = Consultation
        fields = ('resultat',)
        widget = {
                    'resultat': forms.Textarea,
                }

main/templates/main/ajout_fichier.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{{ user.username }}</title>
	{% include "main/includes/css.html" %}

</head>
<body>
{% include "main/includes/navbar_medecin.html" %}<br><br><br>
<div class="row center">
	<h4 class="purple-text darken-1">
		Veuillez insérer les données que vous possédez à travers la saisie manuelle <br>ou à travers un fichier csv prêt
		<br>
	</h4>
</div>
<br>

<div class="row">
	<div class="col s12">
		<div class="col s8  z-depth-5 card">
			<form enctype="multipart/form-data" method="post">
				{% csrf_token %}
				<!--<div class="row">
					<div class="col s6 offset-s3">


						<p><label for="id_region">Region:</label>
						<div class="select-wrapper">
							<select id="id_region" name="region" tabindex="-1">
								<option disabled selected="" value="">Selectionnez votre région</option>
								<option value="Tunis">Tunis</option>

								<option value="Ariana">Ariana</option>

								<option value="Mannouba">Mannouba</option>

								<option value="Ben Arous">Ben Arous</option>

								<option value="Bizerte">Bizerte</option>

								<option value="Nabeul">Nabeul</option>

								<option value="Zaghouan">Zaghouan</option>

								<option value="Beja">Beja</option>

								<option value="Jendouba">Jendouba</option>

								<option value="Le Kef">Le Kef</option>

								<option value="Siliana">Siliana</option>

								<option value="Kairouan">Kairouan</option>

								<option value="Sousse">Sousse</option>

								<option value="Mahdia">Mahdia</option>

								<option value="Monastir">Monastir</option>

								<option value="Kasserine">Kasserine</option>

								<option value="Sfax">Sfax</option>

								<option value="Gabes">Gabes</option>

								<option value="Kebili">Kebili</option>

								<option value="Gafsa">Gafsa</option>

								<option value="Sidi Bouzid">Sidi Bouzid</option>

								<option value="Tozeur">Tozeur</option>

								<option value="Medenine">Medenine</option>

								<option value="Tataouin">Tataouin</option>

							</select></div>
						</p>
					</div>



				</div>-->
				<div class="row">
					<div class="col s4">
						<p><label for="id_grippe_enfant">Nombre de cas de grippe pour les bébés:</label>
							<input id="id_grippe_enfant" name="grippe_enfant" value="0" required="" step="any" type="number">
						</p>
					</div>
					<div class="col s4">
						<p><label for="id_sari_enfant">Nombre de cas SARI pour les bébés:</label>
							<input id="id_sari_enfant" name="sari_enfant" required="" value="0" step="any" type="number">
						</p></div>
					<div class="col s4">
						<p><label for="id_consultation_enfant">Nombre de consultations pour les bébés:</label>
							<input id="id_consultation_enfant" name="consultation_enfant" value="0" required="" step="any"
								   type="number">
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col s4">
						<p><label for="id_grippe_adolescent">Nombre de cas de grippe pour les enfants:</label>
							<input id="id_grippe_adolescent" name="grippe_adolescent" required="" value="0" step="any"
								   type="number">
						</p></div>
					<div class="col s4">
						<p><label for="id_sari_adolescent">Nombre de cas SARI pour les enfants:</label>
							<input id="id_sari_adolescent" value="0" name="sari_adolescent" required="" step="any"
								   type="number">
						</p></div>
					<div class="col s4">
						<p><label for="id_consultation_adolescent">Nombre de consultations pour les enfants:</label>
							<input id="id_consultation_adolescent" value="0" name="consultation_adolescent" required=""
								   step="any"
								   type="number">
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col s4">
						<p><label for="id_grippe_mur">Nombre de cas de grippe pour les murs:</label>
							<input id="id_grippe_mur" name="grippe_mur" value="0" required="" step="any"
								   type="number">
						</p></div>
					<div class="col s4">
						<p><label for="id_sari_mur">Nombre de cas SARI pour les murs:</label>
							<input id="id_sari_mur" name="sari_mur" required="" value="0" step="any" type="number">
						</p></div>
					<div class="col s4">
						<p><label for="id_consultation_mur">Nombre de consultations pour les murs:</label>
							<input id="id_consultation_mur" name="consultation_mur" value="0" required="" step="any"
								   type="number">
						</p></div>
				</div>


				<!--<input accept=".csv" type="file"/>--><br>
				<div class="center">
					<button class="btn waves-effect waves-light" id="button" name="button"
							onclick="$('#progress_container').show();" type="submit" value="enter">Ajouter
					</button>
						<br>
					<div class="hero-content center" id='progress_container'>
						<div class="preloader-wrapper big active">
							<div class="spinner-layer spinner-blue">
								<div class="circle-clipper left">
									<div class="circle"></div>
								</div>
								<div class="gap-patch">
									<div class="circle"></div>
								</div>
								<div class="circle-clipper right">
									<div class="circle"></div>
								</div>
							</div>

							<div class="spinner-layer spinner-red">
								<div class="circle-clipper left">
									<div class="circle"></div>
								</div>
								<div class="gap-patch">
									<div class="circle"></div>
								</div>
								<div class="circle-clipper right">
									<div class="circle"></div>
								</div>
							</div>

							<div class="spinner-layer spinner-yellow">
								<div class="circle-clipper left">
									<div class="circle"></div>
								</div>
								<div class="gap-patch">
									<div class="circle"></div>
								</div>
								<div class="circle-clipper right">
									<div class="circle"></div>
								</div>
							</div>

							<div class="spinner-layer spinner-green">
								<div class="circle-clipper left">
									<div class="circle"></div>
								</div>
								<div class="gap-patch">
									<div class="circle"></div>
								</div>
								<div class="circle-clipper right">
									<div class="circle"></div>
								</div>
							</div>
						</div>
						<br>Veuillez patienter un petit instant..
					</div>
				</div>
			</form>
		</div>
		<div class="col s4  z-depth-5 card">
			<br><br>
			<div class="center">
				<img height="200" src="{% static 'main/images/attach.png' %}" width="200">
				<br><br>
				<span class="card-title purple-text darken-2"><strong>Si vous avez dèja un fichier csv prêt <br>cliquez ici</strong></span>
				<br><br><br>
				<a class="waves-effect waves-light btn-large" href="ajout_csv"><i
						class="material-icons">touch_app</i></a><br><br>
			</div>

		</div>
	</div>

	<!--<div id="national">{{ form_prediction.as_p }}</div>
	<div id="regional">{{ form_region.as_p }}</div>-->


</div>


{% include "main/includes/footer.html" %}
{% include "main/includes/js.html" %}
<script>
	$(document).ready(function(){
    $('.sidenav').sidenav();
      });















</script>
<script>
	$(document).ready(function(){
    $('.modal').modal();
    $('.materialboxed').materialbox();
      });















</script>
<script>
    $(document).ready(function(){
      $('select').formSelect();
    });
	document.getElementById("progress_container").style.display = 'none';

	function toggleLiveData(checkbox) {

                if (checkbox.checked) {

//$("#progress_container").show();
                document.getElementById("fichier").style.display = 'block';
                document.getElementById("creation").style.display = 'none';

                } else {

                  //  $("#progress_container").hide();
      document.getElementById("fichier").style.display = 'none';
      document.getElementById("creation").style.display = 'block';
                }

            };












</script>

</body>
</html>

main/templates/main/lire_fichier.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

 {% include "main/includes/css.html" %}

</head>
<body background="{% static 'main/images/back.jpg' %}">
  {% for line in contenu %}
      {% for i in line %}
      {{ i }}
      {% endfor %}
  <br>
  {% endfor %}
</body>
</html>

main/templates/main/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
You are now logged in as a <a href="/">toubib</a>
</body>
</html>

main/templates/main/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

 {% include "main/includes/css.html" %}

</head>
<body background="{% static 'main/images/back_cards.jpg' %}">
  {% include "main/includes/cards.html" %}
  {% include "main/includes/footer.html" %}
  {% include "main/includes/js.html" %}
</body>
</html>

main/templates/main/stats.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{{ user.username }}</title>
	{% include "main/includes/css.html" %}

</head>
<body>
{% include "main/includes/navbar_medecin.html" %}<br>
<h4 class="center purple-text darken-1">
	Veuillez choisir une saison et une catégorie pour pouvoir consulter les données d'une telle année
</h4>

<div class="row">
	<div class="col s6 offset-s3">
		<form enctype="multipart/form-data" method="post">
			{% csrf_token %}

			<p>
				<label for="id_annee"></label>
			<div class="select-wrapper">
				<select id="id_annee" name="annee" tabindex="-1">
					<option disabled selected="" value="">Année</option>
					<option value="09-10">09-10</option>

					<option value="10-11">10-11</option>

					<option value="11-12">11-12</option>

					<option value="12-13">12-13</option>

					<option value="14-15">14-15</option>

					<option value="15-16">15-16</option>

					<option value="16-17">16-17</option>


				</select>
			</div>
			</p>
			<p><label for="id_categorie"></label>
			<div class="select-wrapper">

				<select id="id_categorie" name="categorie" tabindex="-1">
					<option disabled selected="" value="">Catégorie</option>
					<option value="Nombre total des cas">Nombre total des cas</option>

					<option value="Nombre total des cas de grippe par tranches d'âge">Nombre total des cas de grippe par tranches d'âge
					</option>
					<option value="Nombre total des cas SARI par tranches d'âge">Nombre total des cas SARI par tranches d'âge
					</option>

					<option value="Le pourcentage des cas de grippe et SARI">Le pourcentage des cas de grippe et SARI
					</option>

				</select></div>
			</p>
			<br><br>
			<!--<input accept=".csv" type="file"/>-->
			<div class="center">

				<button class="btn waves-effect waves-light" onclick="$('#progress_container').show();" type="submit">
					Afficher
				</button>

			</div>
		</form>
	</div>
</div>
<div class="hero-content center" id='progress_container'>
	<br>
	<div class="preloader-wrapper big active">
		<div class="spinner-layer spinner-blue">
			<div class="circle-clipper left">
				<div class="circle"></div>
			</div>
			<div class="gap-patch">
				<div class="circle"></div>
			</div>
			<div class="circle-clipper right">
				<div class="circle"></div>
			</div>
		</div>

		<div class="spinner-layer spinner-red">
			<div class="circle-clipper left">
				<div class="circle"></div>
			</div>
			<div class="gap-patch">
				<div class="circle"></div>
			</div>
			<div class="circle-clipper right">
				<div class="circle"></div>
			</div>
		</div>

		<div class="spinner-layer spinner-yellow">
			<div class="circle-clipper left">
				<div class="circle"></div>
			</div>
			<div class="gap-patch">
				<div class="circle"></div>
			</div>
			<div class="circle-clipper right">
				<div class="circle"></div>
			</div>
		</div>

		<div class="spinner-layer spinner-green">
			<div class="circle-clipper left">
				<div class="circle"></div>
			</div>
			<div class="gap-patch">
				<div class="circle"></div>
			</div>
			<div class="circle-clipper right">
				<div class="circle"></div>
			</div>
		</div>
	</div>
	<br>Veuillez patienter un petit instant..
</div>
<br><br> <br>
{% if liste %}
<!-- Modal Trigger -->
<div class="row">
	<div class="col offset-s4">
		<a class="waves-effect waves-light btn modal-trigger" href="#liste_regions">Liste des régions épidémiologiques
			de cette
			année</a>
	</div>
</div>
<!-- Modal Structure -->

<div class="modal" id="liste_regions">
	<div class="modal-content">
		<h4>Les regions qu'avaient une année épidémiologique sont</h4>
		<p>
			{% for e in liste_regions %}
			{{ e }}<br>
			{% endfor %}
		</p>

	</div>
	<div class="modal-footer">
		<a class="modal-close waves-effect waves-green btn-flat" href="#!">OK</a>
	</div>
</div>
{% endif %}
{% if option1 %}
{% for e in liste1 %}
<div class="row">
	<div class="col s4 card">
		<img width="450" height="350" class="materialboxed" src="{% static e %}">
	</div>

	{% endfor %}</div>{% endif %}

{% if option2 %}
{% for e in liste2 %}
<div class="row">
	<div class="col s4 card">
		<img width="450" height="350" class="materialboxed" src="{% static e %}">
	</div>

	{% endfor %}</div>{% endif %}

{% if option3 %}
{% for e in liste3 %}
<div class="row">
	<div class="col s4 card">
		<img width="450" height="350" class="materialboxed" src="{% static e %}">
	</div>

	{% endfor %}</div>{% endif %}

{% if option4 %}
{% for e in liste4 %}
<div class="row">
	<div class="col s6 card">
		<img width="675" height="500" class="materialboxed" src="{% static e %}">
	</div>

	{% endfor %}</div>{% endif %}




{% include "main/includes/footer.html" %}
{% include "main/includes/js.html" %}
<script>
	$(document).ready(function(){
    $('.sidenav').sidenav();
      });
	$(document).ready(function(){
    $('.modal').modal();
    $('.materialboxed').materialbox();
      });
    $(document).ready(function(){
      $('select').formSelect();
      $('.fixed-action-btn').floatingActionButton();
    });
	document.getElementById("progress_container").style.display = 'none';


</script>

</body>
</html>